version: "3"
services:
    app:
        build:
            context: ./app
            args:
                - USER=docker
                - PASSWORD=docker
        tty: true
        env_file:
            - .env
